"""
Django settings for tutorial project.

Generated by 'django-admin startproject' using Django 4.2.8.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
import os
import datetime
from dotenv import load_dotenv


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# 환경 변수 로드
load_dotenv()

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-dr81sgamgfoykf&1ftlh3pl#+*#^0&vy9fn%v%#31(ei!%1ke='

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['127.0.0.1', 'localhost']

# CORS 설정
CORS_ALLOWED_ORIGINS = [
    "http://localhost:8080",  # Vue.js 애플리케이션의 주소
]


# Application definition

INSTALLED_APPS = [
    # 기본 Django 앱
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # 추가 앱
    'django_filters',
    'corsheaders',

    # DRF
    'rest_framework',
    'rest_framework.authtoken',  # (옵션) Token 기반 인증용
    'djoser',   # DRF와 통합된 사용자 인증 및 관리

    # django-allauth 관련
    'django.contrib.sites',  # 사이트 관리를 위해 필수
    'allauth',  # allauth 기본 기능
    'allauth.account',  # 계정 관리 기능
    'allauth.socialaccount',  # 소셜 로그인 기능
    'allauth.socialaccount.providers.google',  # Google OAuth2 지원

    # 커스텀 앱
	'quickstart.apps.QuickstartConfig',
    'genericapp',
    'blog'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',  # 반드시 CommonMiddleware 위에 추가
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'allauth.account.middleware.AccountMiddleware',  # 이 줄을 추가
]

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': datetime.timedelta(days=5),  # 액세스 토큰 유효 시간
    'REFRESH_TOKEN_LIFETIME': datetime.timedelta(days=1),  # 리프레시 토큰 유효 시간
    'ROTATE_REFRESH_TOKENS': True,  # 리프레시 토큰 재사용 방지
    'BLACKLIST_AFTER_ROTATION': True,  # 사용된 리프레시 토큰 블랙리스트 처리
}

# DRF - restframwork config
REST_FRAMEWORK = {
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    ),

    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework.authentication.TokenAuthentication',
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),

    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 10
}

AUTHENTICATION_BACKENDS = (
    'django.contrib.auth.backends.ModelBackend',
    'allauth.account.auth_backends.AuthenticationBackend',
)

SOCIALACCOUNT_PROVIDERS = {
    'google': {
        'SCOPE': [
            'profile',
            'email',
        ],
        'AUTH_PARAMS': {
            'access_type': 'online',
        },
    }
}

ROOT_URLCONF = 'tutorial.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'tutorial.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# 로그인 관련 URL
LOGIN_REDIRECT_URL = '/'  # 로그인 후 리다이렉트될 URL
LOGOUT_REDIRECT_URL = '/'  # 로그아웃 후 리다이렉트될 URL

# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True

SITE_ID = 3

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'static')

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
        },
        'file': {
            'level': 'DEBUG',
            'class': 'logging.FileHandler',
            'filename': 'debug.log',  # 로그 파일 경로
        },
    },
    'loggers': {
        'django': {
            'handlers': ['console', 'file'],
            'level': 'INFO',
            'propagate': True,
        },
        'genericapp': {  # genericapp 모듈의 로깅 설정
            'handlers': ['console', 'file'],
            'level': 'INFO',  # 최소 로그 수준
            'propagate': False,
        },
    },
}

ADM_EMAIL_ADDRESS = os.getenv('ADM_EMAIL_ADDRESS')
ADM_EMAIL_PASSWD = os.getenv('ADM_EMAIL_PASSWD')

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'  # Gmail SMTP 서버 주소
EMAIL_PORT = 587  # Gmail의 SMTP 포트 (TLS)
EMAIL_USE_TLS = True  # TLS 사용
EMAIL_HOST_USER = ADM_EMAIL_ADDRESS  # Gmail 주소
EMAIL_HOST_PASSWORD = ADM_EMAIL_PASSWD  # Gmail 비밀번호
