# Generated by Django 4.2.8 on 2023-12-30 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genericapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchdomain',
            name='value2',
            field=models.CharField(default='Default Name', max_length=1024),
        ),
    ]
