# Generated by Django 4.2.8 on 2024-12-07 06:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('genericapp', '0003_remove_searchdomain_value2'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchdomain',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='search_domains', to=settings.AUTH_USER_MODEL),
        ),
    ]
